### ISSUE TITLE
Why did you go with postgres?

### ISSUE THREAD

**Issue by cs45977** [lukeheath/unicorn#3]
Just curious

**Comment by lukeheath** [comment]
Good question! It was a work around for a Treeline bug that was overwriting everything in api/models/ instead of just the .attribute.json files, which was stopping me from declaring unique indexes on any model attributes. So, I needed to spin out a local Postgres instance so that I could manually set a unique index. This has been fixed in the latest Treeline CLI beta, so i'll switch back to using sails-disk shortly.
